package com.chatter.model;

import java.time.ZonedDateTime;
import java.util.Map;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Type for defining a message within the chat
 */
@DynamoDBTable(tableName = "Message")
public class Message {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String text;
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = MessageUtils.ZonedDateTimeConverter.class )
    private ZonedDateTime dateTime;
    private String fromId;
    private String toId;

    public Message() {}

    @JsonCreator
    public Message(
            @JsonProperty("id") String id,
            @JsonProperty("text") String text,
            @JsonProperty("timestamp") Map<String, String> timestamp,
            @JsonProperty("from") Map<String, String> from,
            @JsonProperty("to") Map<String, String> to)
    {
        this.id = id;
        this.text = text;
        this.dateTime = ZonedDateTime.parse(timestamp.get("dateTime"));
        this.fromId = from.get("id");
        this.toId = to.get("id");
    }

    public Message(String text, String from, String to) {
        this.id = UUID.randomUUID().toString();
        this.text = text;
        this.dateTime = ZonedDateTime.now();
        this.fromId = from;
        this.toId = to;
    }

    public Message(String text, String from, String to, ZonedDateTime dateTime) {
        this.id = UUID.randomUUID().toString();
        this.text = text;
        this.dateTime = dateTime;
        this.fromId = from;
        this.toId = to;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public ZonedDateTime getDateTime() {
        return dateTime;
    }

    public void setDateTime(ZonedDateTime dateTime) {
        this.dateTime = dateTime;
    }

    @DynamoDBAttribute
    public String getFromId() {
        return fromId;
    }

    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    @DynamoDBAttribute
    public String getToId() {
        return toId;
    }

    public void setToId(String toId) {
        this.toId = toId;
    }
}